// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmrjLS9k6PH3l561JCF4zZNTxn3L8Fh1I',
    appId: '1:733403378361:web:7d1f2674f99574c9a72168',
    messagingSenderId: '733403378361',
    projectId: 'cebamer2',
    authDomain: 'cebamer2.firebaseapp.com',
    storageBucket: 'cebamer2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMhwwJakGRi69HYivwSmNimVyJjUWIHss',
    appId: '1:733403378361:android:81dacf34240fee9fa72168',
    messagingSenderId: '733403378361',
    projectId: 'cebamer2',
    storageBucket: 'cebamer2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXw3iJUdJpzK86hsse0d8o2MgjEFbwl2Q',
    appId: '1:733403378361:ios:6b54c837ae029c41a72168',
    messagingSenderId: '733403378361',
    projectId: 'cebamer2',
    storageBucket: 'cebamer2.firebasestorage.app',
    iosClientId: '733403378361-n9kdv2gaevs15vl26e4pub2a7upkvag8.apps.googleusercontent.com',
    iosBundleId: 'com.cebamer.bana.cebamer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXw3iJUdJpzK86hsse0d8o2MgjEFbwl2Q',
    appId: '1:733403378361:ios:6b54c837ae029c41a72168',
    messagingSenderId: '733403378361',
    projectId: 'cebamer2',
    storageBucket: 'cebamer2.firebasestorage.app',
    iosClientId: '733403378361-n9kdv2gaevs15vl26e4pub2a7upkvag8.apps.googleusercontent.com',
    iosBundleId: 'com.cebamer.bana.cebamer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmrjLS9k6PH3l561JCF4zZNTxn3L8Fh1I',
    appId: '1:733403378361:web:207aa88ac502c145a72168',
    messagingSenderId: '733403378361',
    projectId: 'cebamer2',
    authDomain: 'cebamer2.firebaseapp.com',
    storageBucket: 'cebamer2.firebasestorage.app',
  );

}